name: CSS Linting Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install stylelint and config
        run: npm install -g stylelint stylelint-config-standard
      - name: Run stylelint
        run: stylelint "**/*.css"
