name: First Interaction
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - name: First Interaction Action
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Welcome to the repository! Thanks for opening an issue.
            We will review it as soon as possible.
          pr-message: >
            Thank you for your pull request! A team member will review it shortly.
