# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!
   
  # End additional job steps!!
  lint:
    runs-on: ubuntu-latest
    steps:
      #Step 1 Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Add steps here!!
      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Step 3: Install ESLint
      - name: Install ESLint
        run: npm install eslint

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npx eslint . || echo "Linting completed with warnings or errors."
      
      # Step 5: HTML Proofer
      - name: HTMLproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: ./
          continue-on-error: true

      # Step 6: GitHub - Activity - Readme
        # - Updates README with the recent GitHub activity of a user
        # - Learn more about this action here: https://github.com/jamesgeorge007/github-activity-readme
      - name: GitHub - Activity - Readme
        uses: jamesgeorge007/github-activity-readme@v0.4.4

          # End additional steps!!
