# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment (HTMLProofer requires Ruby)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # You can change the Ruby version if needed

    # Step 3: Install HTMLProofer
    - name: Install HTMLProofer
      run: |
        gem install htmlproofer

    # Step 4: Run HTMLProofer
    - name: Run HTMLProofer
      run: |
        htmlproofer ./_site --check-html --disable-external
  # End additional job steps!!
  lint:
    runs-on: ubuntu-latest
    steps:
      #Step 1 Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
      # Add steps here!!
      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install ESLint
      - name: Install ESLint
        run: npm install eslint

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npx eslint . || echo "Linting completed with warnings or errors."
          # End additional steps!!
