name: Security Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Trivy
      - name: Vulnerability scan
        uses: wetransform/gha-trivy@v2.3.2